CUDA_VISIBLE_DEVICES=1 python src/train.py \
  --method pis_lp \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project final_lj13 \
  --energy lj13 \
  --mode_fwd pis \
  --langevin \
  --batch_size 16 \
  --max_grad_norm 1.0 \
  --clipping \
  --epochs 10000 \