CUDA_VISIBLE_DEVICES=2 python src/train.py \
  --method subtb_lp \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project final_lj13 \
  --energy lj13 \
  --mode_fwd subtb \
  --lr_flow 0.0005 \
  --langevin \
  --partial_energy \
  --conditional_flow_model \
  --batch_size 16 \
  --max_grad_norm 1.0 \
  --clipping \
  --epochs 10000 \
