CUDA_VISIBLE_DEVICES=4 python src/train.py \
  --method tb_expl_ls \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project final_lj13 \
  --teacher mala \
  --energy lj13 \
  --local_search \
  --both_ways \
  --burn_in 50 \
  --max_iter_ls 2000 \
  --teacher_batch_size 500 \
  --ld_schedule \
  --exploratory \
  --exploration_wd \
  --exploration_factor 0.1 \
  --max_grad_norm 1.0 \
  --clipping \
  --epochs 10000 \
