CUDA_VISIBLE_DEVICES=6 python src/train.py \
  --method tb_ls \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project final_lj13 \
  --teacher mala \
  --energy lj13 \
  --local_search \
  --both_ways \
  --burn_in 50 \
  --max_iter_ls 2000 \
  --teacher_batch_size 500 \
  --max_grad_norm 1.0 \
  --ld_schedule \
  --clipping \
  --epochs 10000 \
