CUDA_VISIBLE_DEVICES=4 python src/train.py \
  --method tb_expl_ls \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project lj55 \
  --teacher mala \
  --energy lj55 \
  --local_search \
  --both_ways \
  --burn_in 100 \
  --max_iter_ls 4000 \
  --teacher_batch_size 200 \
  --ld_schedule \
  --exploratory \
  --exploration_wd \
  --batch_size 4 \
  --exploration_factor 0.1 \
  --max_grad_norm 1.0 \
  --clipping \
