CUDA_VISIBLE_DEVICES=2 python src/train.py \
  --method subtb_lp \
  --date $(date +%Y-%m-%d_%H:%M:%S) \
  --project aldp \
  --mode_fwd subtb \
  --energy aldp \
  --langevin \
  --partial_energy \
  --conditional_flow_model \
  --batch_size 16 \
  --clipping \